AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description:
  Sample SAM Template for DynamoDB table and IAM role for DynamoDB access via cross-account trust policy
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10
Parameters:
  OrganizationID:
    Type: String
    Default: o-kdmi2yospj
  RoleName:
    Type: String
    Default: DynamoDbRole
  LambdaAssumeRole:
    Type: String
    Default: arn:aws:iam::421275677139:role/crud-api-with-cross-account-dynamodb-st-LambdaRole-L650MMPAUE2Z
    # Replace this role ARN with the ARN of the role in the account where your Lambda functions are deployed

Resources:
  UserTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      TableName: !Sub ${AWS::StackName}-UserTable

  AssumeRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref RoleName
      Policies:
          -
            PolicyName: "TableAdminUserExample"
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                -
                  Effect: "Allow"
                  Action: "*"
                  Resource: !GetAtt UserTable.Arn
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            # "AWS": !Sub ${LambdaAssumeRole} # Use for explicit Lambda role trust which is more secure
            "AWS": "421275677139" # Allows any IAM role from the allow-listed accounts to assume this role
            # "AWS": "*" # Allows any authenticated IAM principal to assume this role assuming it also meets any specified conditions
          Action:
          - sts:AssumeRole
          Condition:
            ForAnyValue:StringLike:
              aws:PrincipalOrgPaths:
                - !Sub "${OrganizationID}/*"

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  DynamoDBRoleName:
    Description: "Cross-account IAM Role for DynamoDB Name"
    Value: !Ref AssumeRole
  DynamoDBRoleArn:
    Description: "Cross-account IAM Role for DynamoDB ARN"
    Value: !GetAtt AssumeRole.Arn
  AccountId:
    Description: "Account ID"
    Value: !Ref "AWS::AccountId"
  DynamoDBTableArn:
    Description: "DynamoDB User Table ARN"
    Value: !GetAtt UserTable.Arn
  DynamoDBTableName:
    Description: "DynamoDB User Table Name"
    Value: !Ref UserTable
